version: '3'
services: 
    http:
        build: ./source/
        volumes:
            - ./source/:/usr/src/app/
        ports: 
            - 8080:8080
        environment: 
            PORT: 8080
            #Flask non richiede di essere riavviato a ogni modifica
            FLASK_DEBUG: 1
